kind: pipeline
type: docker
name: default

steps:
  - name: tag image
    image: debian:bullseye-slim
    commands:
      - apt-get update
      - apt-cache show samba | grep Version | awk '{print $2}' | sed -e 's/^[^:]*://g' -e 's/\+dfsg//g' > .tags
      - echo ",latest" >> .tags
  - name: docker
    image: plugins/docker
    settings:
      repo: harbor.home.hoffmeister.biz/diztortion/samba
      registry: harbor.home.hoffmeister.biz
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
