kind: pipeline
type: docker
name: default

steps:
  - name: tag image
    image: harbor.home.hoffmeister.biz/docker.io-cache/library/debian:bullseye-slim
    commands:
      - apt-get update
      - apt-cache show samba | grep Version | head -n 1 | awk '{print $2}' > .tags
      - echo ",latest" >> .tags
  - name: docker
    image: harbor.home.hoffmeister.biz/docker.io-cache/plugins/kaniko
    settings:
      repo: harbor.home.hoffmeister.biz/diztortion/samba
      registry: harbor.home.hoffmeister.biz
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
